CREATE TABLE [CheckIn_Details]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Term] SMALLINT NOT NULL, 
    [SID] CHAR(9) NOT NULL, 
    [Lesson] SMALLINT NOT NULL, 
    [Date] DATE NOT NULL DEFAULT CONVERT(DATE,GETDATE()), 
    [CheckIn] TIME(0) NULL DEFAULT CONVERT(TIME(0),GETDATE()) , 
    [CheckOut] TIME(0) NULL, 
    [Change] TIME(0) NULL, 
    [Keep] TIME(0) NULL DEFAULT CONVERT(TIME(0),GETDATE()), 
    [LateState] BIT NOT NULL DEFAULT 0, 
    [CheckOutState] BIT NOT NULL DEFAULT 0, 
    [State] NVARCHAR(50) NULL, 
    [Note] NVARCHAR(MAX) NULL
)
