CREATE TABLE [CheckIn_Details]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Term] SMALLINT NOT NULL DEFAULT F_Term(), 
    [ID] INT NOT NULL, 
	[IP] VARCHAR(15) NOT NULL DEFAULT '0.0.0.0',
    [Lesson] TINYINT NOT NULL, 
    [Date] DATE NOT NULL DEFAULT CONVERT(DATE,GETDATE()), 
    [CheckIn] TIME(0) NULL DEFAULT CONVERT(TIME(0),GETDATE()) , 
    [CheckOut] TIME(0) NULL, 
    [Change] TIME(0) NULL, 
    [Keep] TIME(0) NULL DEFAULT CONVERT(TIME(0),GETDATE()), 
    [LateState] BIT NOT NULL DEFAULT 0, 
    [CheckOutState] BIT NOT NULL DEFAULT 0, 
    [State] TINYINT NULL, 
    [Note] NVARCHAR(MAX) NULL, 
    CONSTRAINT [FK_CheckIn_Details_Student] FOREIGN KEY ([ID]) REFERENCES [Student]([ID])
)
