CREATE TABLE [dbo].[Final]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Term] SMALLINT NOT NULL, 
    [SID] CHAR(9) NOT NULL, 
    [Date] DATE NOT NULL DEFAULT GETDATE(), 
    [State] NVARCHAR(50) NOT NULL
)
