CREATE TABLE [dbo].[Final]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Term] SMALLINT NOT NULL DEFAULT F_Term(), 
    [ID] INT NOT NULL, 
    [Date] DATE NOT NULL DEFAULT GETDATE(), 
    [State] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [FK_Final_Student] FOREIGN KEY ([ID]) REFERENCES [Student]([ID])
)
