CREATE TABLE [dbo].[Staff]
(
	[SEAID] SMALLINT NOT NULL PRIMARY KEY, 
	[ID] INT NOT NULL,
    [Name] NVARCHAR(50) NOT NULL, 
    [Time] DATE NOT NULL DEFAULT GETDATE(), 
    [EndTime] DATE NOT NULL DEFAULT '2099-12-31', 
    CONSTRAINT [FK_Staff_Student] FOREIGN KEY ([ID]) REFERENCES [Student]([ID])
)
