CREATE TABLE [dbo].[Table_Disobey_Certificate]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL  DEFAULT NEWID(), 
    [ID] CHAR(9) NOT NULL, 
    [College] CHAR(2) NOT NULL, 
    [Date] DATE NOT NULL, 
	[InputDate]	DATETIME NOT NULL DEFAULT CONVERT(DATETIME,GETDATE()),
	[Done] BIT NOT NULL DEFAULT 0,
    [Valid] BIT NOT NULL DEFAULT 0, 
    [Note] NVARCHAR(MAX) NULL
)
