CREATE TABLE [dbo].[Table_Checkin_Details]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[ID] CHAR(9) NOT NULL,
    [Date] DATE NOT NULL DEFAULT CONVERT(DATE,GETDATE()), 
	[Lesson] NCHAR(2) NOT NULL,
    [Signin] TIME(0) NULL DEFAULT CONVERT(TIME(0),GETDATE()), 
    [Signout] TIME(0) NULL, 
    [Change] TIME(0) NULL, 
    [Keep] TIME(0) NULL, 
    [Signin_State] INT NULL, 
    [State] INT NOT NULL DEFAULT 0
)

GO

CREATE TRIGGER [dbo].[Trigger_Table_Checkin_Details_Update]
    ON [dbo].[Table_Checkin_Details]
    FOR DELETE, UPDATE
    AS
    BEGIN
        SET NoCount ON
		DECLARE @OLD NVARCHAR(MAX), @NEW NVARCHAR(MAX), @LOGTYPE NVARCHAR(MAX), @MANAGER NVARCHAR(MAX), @GUID UNIQUEIDENTIFIER
		SELECT @GUID=OLD.GUID, @OLD=OLD.State, @NEW=NEW.State FROM DELETED AS OLD FULL JOIN INSERTED AS NEW ON OLD.ID=NEW.ID
		SELECT @LOGTYPE='DELETE' FROM DELETED
		SELECT @LOGTYPE='UPDATE' FROM INSERTED
		SELECT @MANAGER=SYSTEM_USER
		INSERT INTO Table_Manage_Checkin VALUES(@GUID, @LOGTYPE, @OLD, @NEW, @MANAGER)
    END