CREATE TABLE [dbo].[Table_Disobey_Details]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL, 
    [ID] CHAR(9) NOT NULL, 
    [Date] DATETIME NOT NULL DEFAULT CONVERT(DATETIME,GETDATE()), 
	[Class] INT NOT NULL,
    [Type] INT NOT NULL, 
	[Manager] NVARCHAR(MAX) NOT NULL,
    [Note] NCHAR(10) NULL 
)
