CREATE VIEW [dbo].[View_List_CheckIn]
	AS 
WITH
CTE AS(
SELECT ID,State,COUNT(State) AS [COUNT]
FROM [CheckIn_Details]
GROUP BY ID,STATE
)
SELECT ID,
		ISNULL((SELECT [COUNT] FROM CTE WHERE [State]=1 AND ID=CTEOR.ID),0) [NORMAL],
		ISNULL((SELECT [COUNT] FROM CTE WHERE [State]=2 AND ID=CTEOR.ID),0) [LATE],
		ISNULL((SELECT [COUNT] FROM CTE WHERE [State]=3 AND ID=CTEOR.ID),0) [TRUENCY]
		FROM CTE CTEOR
